### ISSUE TITLE
Use socks-client instead of rainbowsocks for socks:// protocol

### ISSUE THREAD

**Issue by andyhu** [TooTallNate/superagent-proxy#11]
Hi, thanks for your awesome work!
I found that in this module it's using rainbowsocks when the proxy protocol is set to `socks://`. However, rainbowsocks only support socks 4a which is a very limited and outdated version. Now nearly everyone uses socks 5. Can we replace it with https://github.com/JoshGlazebrook/socks-client? It does support all versions of socks protocol including socks 4, 4a and 5.

Please check the demo code they provided below:
```js
var socksAgent = new SocksClient.Agent({
    proxy: {
        ipaddress: "202.101.228.108",
        port: 1080,
        type: 5,
    },
    true, // we are connecting to a HTTPS server, false for HTTP server
    false // rejectUnauthorized option passed to tls.connect(). Only when secure is set to true
});

http.get({ hostname: 'google.com', port: '443', agent: socksAgent}, function (res) {
    // Connection header by default is keep-alive, we have to manually end the socket
    socksAgent.encryptedProxy.end();
});
```

**Comment by TooTallNate** [comment]
That would be fine with me. Pull request much appreciated!

**Comment by andyhu** [comment]
OK, PR submitted. Thanks for the quick response :)
