### ISSUE TITLE
add support for superagent 1.1.0

### ISSUE THREAD

**Issue by jconley** [TooTallNate/superagent-proxy#12]
add support for superagent 1.0+

also:
```
$ npm install
npm WARN peerDependencies The peer dependency superagent@>= 0.15.4 && < 1 included from superagent-proxy will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

**Comment by jimmy-vargas-jala** [comment]
Hello,

I am having the same problem... is there any plan to get this fixed soon?

11350 error peerinvalid The package superagent does not satisfy its siblings' peerDependencies requirements!
11350 error peerinvalid Peer superagent-proxy@0.3.1 wants superagent@>= 0.15.4 && < 1

**Comment by Jxck** [comment]
+1

**Comment by madmod** [comment]
+1

**Comment by madmod** [comment]
Fyi you can use the pull request from @Jxck for now like this.
npm i git://github.com/Jxck/superagent-proxy#1cbf634745b04df4f2bddbba773eb716e7e1e117

**Comment by TooTallNate** [comment]
v0.3.2 published to npm. Sorry for the delay!
