### ISSUE TITLE
Supports for conditional proxy?

### ISSUE THREAD

**Issue by reyou** [TooTallNate/superagent-proxy#18]
I have following code;

// if config is enabled return http://127.0.0.1:8888
// else return null
var proxy = process.env.http_proxy || config.getProxyAddress();

  request
        .get(url)
        .proxy(proxy)
        .set('Authorization', 'Bearer ' + authCode)

here if I pass proxy as null or empty string it throws error of: "TypeError: an HTTP(S) proxy server `host` and `protocol` must be specified!" but I would like to depend on my config settings.

How can I enable this? 

In this case, if proxy is null or empty can we just bypass and do not use proxy?

**Comment by TooTallNate** [comment]
I would just not call `.proxy()` if your `proxy` var is falsey:

``` js
// if config is enabled return http://127.0.0.1:8888
// else return null
var proxy = process.env.http_proxy || config.getProxyAddress();

var req = request.get(url)
  .set('Authorization', 'Bearer ' + authCode);

if (proxy) req.proxy(proxy);
```

**Comment by reyou** [comment]
Actually this pull request does exactly what I am asking for;

https://github.com/TooTallNate/superagent-proxy/pulls

Is it possible to accept it?

**Comment by hughmp** [comment]
This works for me:

```JS
request
  .get(url)
  .proxy(proxy ? proxy : url)
  .set('Authorization', 'Bearer ' + authCode)
```

Does it work for others?

**Comment by hughmp** [comment]
realised this doesn't work as intended when `url` is using `https` :-1:
