### ISSUE TITLE
Bump `proxy-agent` to "^3.0.1"

### ISSUE THREAD

**Issue by abelino** [TooTallNate/superagent-proxy#34]
In light of https://snyk.io/test/github/auth0/auth0-authorization-extension/60b5fff68315ad7a01a4ded36e50c24ecc1fbd70?tab=issues#SNYK-JS-HTTPSPROXYAGENT-469131 I would like to thank you for making the appropriate changes in `pac-proxy-agent`, `proxy-agent`. But it seems like we also need to update this package since v2.0.0 of `superagent-proxy` is pinned down to v3.0.0 of `proxy-agent` as seen [here](https://github.com/TooTallNate/superagent-proxy/blob/master/package.json#L29). We simply need to either update `procy-agent` to `3.0.1` if you want a pinned version for some reason or `^3.0.1`.

**Comment by nzacca** [comment]
Should be resolved by this PR: https://github.com/TooTallNate/superagent-proxy/pull/35

**Comment by luisnaranjo733** [comment]
This issue can be closed and that PR can be abandoned since superagent-proxy already targets "proxy-agent@3" which includes "proxy-agent@3.1.1" which is the version that already has the fix.

If the issue isn't solved for you, you should be able to solve it by refreshing your lock file.

**Comment by abelino** [comment]
Closing
