### ISSUE TITLE
Issue while running `npm uninstall`. (Error: Command failed: fatal: Unable to look up github.com (port 9418)) )

### ISSUE THREAD

**Issue by satyarth** [TooTallNate/superagent-proxy#9]
Am just doing the basic `npm install`.But i keep getting these errors (image attached).
![errors](https://cloud.githubusercontent.com/assets/6491284/5812675/8f79cfd8-a095-11e4-8001-d5e8d6dda158.JPG)

**Comment by TooTallNate** [comment]
Sorry, I don't think this is an issue with this module. Check your internet connection.
